name: Aristeas UniversalUpload Test
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4.1.4
      - id: set-matrix
        run: bash ModIdFinder.sh >> $GITHUB_OUTPUT
  
  login:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 244850
          login: true
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.accountname }}
          STEAM_PASSWORD: ${{ secrets.password }}
  
  workshop-upload:
    needs: [setup, login]
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4.1.4
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 244850
          publishedFileID: ${{ matrix.value }}
          path: ${{ matrix.path }}
          changelog: ${{ github.event.head_commit.message }}
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.accountname }}
          STEAM_PASSWORD: ${{ secrets.password }}