name: Aristeas UniversalUpload Test
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**/modinfo.sbmi'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4.1.4
      - id: set-matrix
        run: |
          modPath=$(dirname ${{ github.event.path }})
          modId=$(grep -oP '(?<=<Id>)[^<]+' "${{ github.event.path }}")
          echo "matrix={\"include\":[{\"value\":\"$modId\",\"path\":\"$modPath\"}]}" >> $GITHUB_OUTPUT
  
  workshop-upload:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4.1.4
      - name: Delay
        run: sleep $((${{ strategy.job-index }} * 10))
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 244850
          login: true
          publishedFileID: ${{ matrix.value }}
          path: ${{ matrix.path }}
          changelog: ${{ github.event.head_commit.message }}
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.accountname }}
          STEAM_PASSWORD: ${{ secrets.password }}